### ISSUE TITLE
conflict doctrine module for version 3.4.0

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-twigrenderer#26]
`composer require  dotkernel/dot-twigrenderer:3.4.0
./composer.json has been updated
Running composer update dotkernel/dot-twigrenderer
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/doctrine-module[5.1.0, ..., 5.2.1] require doctrine/collections ^1.6.8 -> found doctrine/collections[1.6.8, ..., 1.8.0] but the package is fixed to 2.1.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - doctrine/doctrine-module 5.3.0 requires doctrine/collections ^1.8.0 -> found doctrine/collections[1.8.0] but the package is fixed to 2.1.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - dotkernel/dot-twigrenderer 3.4.0 requires doctrine/doctrine-module ^5.1 -> satisfiable by doctrine/doctrine-module[5.1.0, ..., 5.3.0].
    - Root composer.json requires dotkernel/dot-twigrenderer 3.4.0 -> satisfiable by dotkernel/dot-twigrenderer[3.4.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

**Comment by bidi47** [comment]
obsolete
was resolved in https://github.com/dotkernel/dot-twigrenderer/issues/37
