### ISSUE TITLE
Bump to PHP 8.3

### ISSUE THREAD

**Issue by bidi47** [dotkernel/dot-twigrenderer#35]

**Comment by bidi47** [comment]
blocked by
mezzio/mezzio-twigrenderer
dotkernel/dot-navigation (dotkernel/dot-authorization)
doctrine/doctrine-module

**Comment by arhimede** [comment]
blocked by https://github.com/mezzio/mezzio-twigrenderer/pull/33

**Comment by arhimede** [comment]
support for 8.3 now 
https://github.com/mezzio/mezzio-twigrenderer/releases/tag/2.15.0

**Comment by bidi47** [comment]
the upgrade to 8.3 is still blocked by
doctrine/doctrine-module

**Comment by arhimede** [comment]
doctrine_module updated to 8.3 
https://github.com/doctrine/DoctrineModule/pull/828

**Comment by bidi47** [comment]
https://github.com/dotkernel/dot-twigrenderer/pull/36

**Comment by arhimede** [comment]
closed in #36
