### ISSUE TITLE
remove doctrine-module

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-twigrenderer#37]
**dot-twigrender**  require 
     **doctrine -module** which require 
         **laminas -cache** which require 
              **psr/cache 1.0**

conflict with **roave/psr-container-doctrine**  which require 
                       psr/cache 2 or 3 

@alexmerlin  we need advice here

**Comment by alexmerlin** [comment]
Do you want to remove `doctrine/doctrine-module` and add `roave/psr-container-doctrine` to `dot-twigrenderer`, but it throws a conflict on `psr/cache`?
If not, please explain what are you trying to achieve and what errors are you getting.

**Comment by bidi47** [comment]
no, we don't want to add new dependencies to dot-twigrenderer. in fact, we are considering removing laminas/laminas-authentication and dotkernel/dot-authorization as well as doctrine/doctrine-module

the conflict occurred when i tried to update the admin project to PHP 8.3
dot-twigrenderer requires doctrine/doctrine-module which requires laminas/laminas-cache which requires psr/cache v1
roave/psr-container-doctrine requires psr/cache v2 or v3

**Comment by alexmerlin** [comment]
If you're sure that it is safe to do so, then you should remove all the unnecessary packages (including any code referencing them), make a new `dot-twigrenderer` release, then continue updating the admin.

**Comment by arhimede** [comment]
In November 2021 , we remove doctrine-module from frontend ...
https://github.com/dotkernel/frontend/pull/239

**Comment by bidi47** [comment]
doctrine-module is removed in https://github.com/dotkernel/dot-twigrenderer/pull/39
