### ISSUE TITLE
Replace usage of `twig_date_converter` with own solution

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/dot-twigrenderer#46]
**The issue:**
- Function 'twig_date_converter' is deprecated
- Function 'twig_date_converter' is marked as @ internal

**Where:**
File: `src/Extension/DateExtension.php`
Lines: `43`-`44`

**Recommendation from vendor:**
_None_

**Todo:**
- Find a solution to achieve the same results with our own function directly in the `DateExtension` class.
- Remove file `psalm-baseline.xml`
- Remove line `errorBaseline="psalm-baseline.xml"` from `psalm.xml`

**Comment by bidi47** [comment]
resolved in 
https://github.com/dotkernel/dot-twigrenderer/pull/48
